Massively optimise hydro and dragon egg gens
ProfElements/DynaTech pull request #90
Opened 2021-06-05 18:46 UTC by WalshyDev

There have been multiple improvements in this PR:
* Massively improved hydro gens
  - Use a Guava Cache to cache the energy values. These will be refreshed every 1 min (ish).
  - Remove the BlockStorage stuff which is SLOW - BlockStorage serializes and deserializes a ton which is slow.
* Optimised Chipping Generator
  - getProgressBar was returning a NEW object everytime, fixed that
  - Avoid any expensive item checks (with != null, != air, etc)
  - Avoid multiple calls to getItemMeta - getItemMeta will do **multiple** clones, it's slow! Make sure to only ever do this once
* Optimised dragon egg gen
  - The things you did to try and optimise this just slow it down. While creating a new Block instance isn't great it's a hell of a lot quicker than a lot of BlockStorage stuff
* Fixed general formatting issues and inconsistencies

2021-06-05 20:29 UTC, TheBusyBiscuit requested changes
You committed an empty file again...

Otherwise: wooooh 🎉

2021-06-05 21:24 UTC, WalshyDev commented
> You committed an empty file again...
> 
> Otherwise: wooooh 🎉

That wasn't even me! Prof did that! I deleted it! *grrrrrr*

2021-06-06 03:34 UTC, ProfElements commented
:eyes: I didnt think the workflow would fail :/

2021-06-06 07:09 UTC, WalshyDev commented
That's what happens when you change something at like midnight on phone :p

I didn't realise you were using CSLib's Config which doesn't support default

2021-06-06 15:55 UTC, merged